### ISSUE TITLE
Plug In Crashed  when trying to export layers

### ISSUE THREAD

**Issue by tarniks** [khalim19/gimp-plugin-export-layers#14]
I keep getting the error msg:

pythonw.exe has stopped working 

followed by:

Plug-in crashed: "export_layers.py"
(C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\export_layers.py)

This occurs everytime I try to export layers from an image.  I've uninstalled/reinstalled GIMP and verified the export layers plug ins were in the correct location but keep getting the same error messages?

**Comment by SoyYuma** [comment]
I get the same error that @tarniks reported every time I click on "Export Layers" or try to show the advanced options. I've enabled both debug and preprocessing debug. The log is in:

https://gist.github.com/SoyYuma/dfc8b997c98981e1688f

Looks like the crash error has not been registered? I only seem to get warnings about missing icons and objects not being g_objects? Sorry, I'm not longer familiar with GTK.

BTW I'm using Gimp 2.8.14 in Windows. It bundles with python 2.7.5.

Let me know if I can do anything to help :-)

**Comment by SoyYuma** [comment]
In my bug hunting expedition I tried running gimp from the command prompt using --verbose and --console-messages. I expected to get more info on why it's crashing, but instead **the plugin worked!**

I got this message on the Gimp output console though:

    INIT: gimp_real_restore
    Parsing 'c:\Users\soy_yuma\.gimp-2.8\pluginrc'
    Querying plug-in: 'c:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins\pyconsole.py'
    Querying plug-in: 'c:\Users\soy_yuma\.gimp-2.8\plug-ins\export_layers'
    GIMP-Error: Unable to run plug-in "export_layers"
    (c:\Users\soy_yuma\.gimp-2.8\plug-ins\export_layers)

    Failed to execute child process (No such file or directory)

    Initializing plug-in: 'C:\Users\soy_yuma\.gimp-2.8\plug-ins\export_layers.py'
    Writing 'c:\Users\soy_yuma\.gimp-2.8\pluginrc'

**Comment by Pingponguin** [comment]
I had the same problem. Using Gimp 2.8.14 with Win 8.1 64Bit
I tried version 2.1 and 2.2 both crashed.
Than I made a new Gimp 2.8.14 installation with overiting the existing installation and the plugin works just perfect.

Thanks for the great plugin.

**Comment by anasik** [comment]
For me, it supposedly starts exporting layers but never successfully exports even the first and basically gimp freezes right there.

**Comment by khalim19** [comment]
For those of you who experience crashes when exporting layers or clicking the Advanced Settings button, try reinstalling GIMP. I got a mail from a user who had the same issue, and reinstalling GIMP fixed it for him.

**Comment by ruipimentel** [comment]
Good afternoon, like other users I am unable to export layers. I'm running GIMP 2.8.10 over Ubuntu 14.10, and have already uninstalled/reinstalled GIMP as suggested.

As soon as I click the "Export Layers" button on the file selection dialog window (even without having clicked the Advanced Settings button at all), the progress bar appears but doesn't move.

![captura de tela de 2015-11-05 13 47 59](https://cloud.githubusercontent.com/assets/4542150/10973681/8d4e7308-83c5-11e5-892b-1e6c377d97b8.png)

Following khalim19's instructions, I ran his test script on all three GUI's, but none of them rendered any buttons (even the standard "Close window" button was absent, leaving me with the "ESC" key as the only option to exit the dialog). Despite of that, the log doesn't show any errors.

!["Results" for the first GUI option](https://cloud.githubusercontent.com/assets/4542150/10974144/c6df7b42-83c7-11e5-96ca-3f7cb4f134f0.png)

![Screen capture from the log file (unfortunately I was unable to upload the text original due to GitHub restrictions)](https://cloud.githubusercontent.com/assets/4542150/10973746/daaf18b4-83c5-11e5-8fb0-481c7db7a824.png)

The closest I can get from obtaining some feedback on the error is this message, which appears on the Terminal when I execute GIMP from there. The error appears **while loading** GIMP, way **before** image selection and actual plugin usage.

![Error right after issuing "gimp" command on Terminal (before actual plugin usage)](https://cloud.githubusercontent.com/assets/4542150/10973879/8ad204c2-83c6-11e5-9cd9-f7d6f9cb84e0.png)

It's worth mentioning that I have already "chown"'d and granted "777" permission to all of the plugin files.

Is there any other procedure I could follow in order to help diagnosing this issue?

Thanks in advance for any assistance! :)

**Comment by waystar** [comment]
I've been using the plug-in at work on Windows 7 machines with no problem for weeks. Now I'm trying to use it at home with Gimp. 2.8.10 on Linux Mint 17.2 Cinnamon edition. I am experiencing the same failure as that of ruipimentel. It hangs before it starts to save the first layer. Permissions are good, Python is correct, tried reinstalling Gimp, tried running from command line (both user and superuser). Same results. 
I'll keep watching to try any further suggestions. Thanks!

**Comment by khalim19** [comment]
First off, thank you both for reporting this and trying out all the methods I suggested. It's very likely it's not the same problem as the users above experienced, though.

Do you use the latest release (2.4)?

I noticed one thing in the screenshots. The Export Layers dialog should have appeared in the bottom panel (well, at least it does on Windows and on Ubuntu with Unity desktop manager). The file format dialog should have also appeared by now. Try moving the Export Layers dialog outside the screen center - the file format dialog might be hidden behind the Export Layers dialog.

If you can't move the dialog (because it's frozen), try alt-tabbing to see if you can get to the file format dialog.

And if the file format dialog didn't appear, then I have no idea what could case the hanging... I'll think up something. For the time being, you can execute the plug-in via the Python-Fu console, that should work well.

The console output can be safely ignored, it's harmless. [I can't do anything about it, though.](https://github.com/khalim19/gimp-plugin-export-layers/issues/12)

**Comment by waystar** [comment]
Success!

The file format dialog is indeed hidden behind the Export Layers dialog.

Thank you!

Waylena M. McCully
Champaign, IL
KD9ASP

**Comment by ruipimentel** [comment]
Indeed!

I didn't know that a new window was supposed to open, but probably due to a GUI issue it did open, only behind the file selection dialog...

![The modal window (on the left) was actually hidden behind the file selection dialog window...](https://cloud.githubusercontent.com/assets/4542150/11031412/76754f46-86bb-11e5-89f4-a3e8744f2052.png)

Upon confirming on the previously hidden modal window, the plugin does export everything nicely.

So... I guess khalim19 is right, my case and waystar's one are probably not the same as the other users', but hopefully these posts will be informative for someone else :)
Thank you both!
And thank you khalim19 for this super handy plugin!!!

**Comment by khalim19** [comment]
Thank you both. The hidden file format dialog bug is definitely an issue, but I haven't found a solution for that.

**Comment by khalim19** [comment]
Closing this as no news was provided to the original issue.
