### ISSUE TITLE
Using folder opacity level to alter what is inside the folders

### ISSUE THREAD

**Issue by Reptorian1125** [khalim19/gimp-plugin-export-layers#41]
Do you think that you can modify the Export Layers code to allow one to use folder opacity level to change the transparency levels of what is inside the folders? Since GIMP doesn't have multiple layer selection, I think this would be a good idea during the meantime.

**Comment by khalim19** [comment]
It's certainly possible, but I feel like it falls outside the scope of the plug-in, which primarily deals with exporting layers, not batch-editing them.

It sounds like something that could be handled by [BIMP](https://github.com/alessandrofrancesconi/gimp-plugin-bimp), although I'm not sure if it supports batch-manipulating layers. If not, I'll think about this request, but it's going to take quite a while before I take a look at this.

**Comment by khalim19** [comment]
Based on [this forum thread](http://gimpforums.com/thread-improving-export-layers-plugin) which I assume you started, I must have misunderstood your request.

Although, I'm still not sure if I understand completely:
a) You want to export an entire layer group as one image while preserving its transparency. This is already doable in the latest revision (not an official release yet, but it's stable) - simply select the desired layer group from the preview, check "Export only selected layers" and hit Export.
b) You want to control the transparency of the underlying layers in the group by adjusting the transparency of the group (instead of individual layers, because it's painful to do this one layer at a time because GIMP doesn't support multi-selection), and you need to export the individual layers with the transparency inherited from the layer group. This is not currently possible, but it's perfectly in the scope of the plug-in. If this is what you request, I think I'll implement this when I release 3.0.

**Comment by Reptorian1125** [comment]
The b part is exactly what I want at the moment, and I have tried BIMP just to find that it doesn't work, but the feature should be available in BIMP. And yes, I did started that thread.

**Comment by khalim19** [comment]
Done. If you want to use the feature now, you can download the latest revision. Check "Show more settings" and then simply check "Inherit transparency from layer groups". Note that each layer inherits the transparency from all of its parents, not just the immediate parent.

Let me know if it works for you. :)

**Comment by Reptorian1125** [comment]
I don't see the "Show More Settings" in the Windows build of GIMP 2. The option isn't under Advanced settings. Sorry this took a while, but I"m studying Industrial Design.

**Comment by khalim19** [comment]
Sorry I wasn't clear - you need to download the [latest work-in-progress version of the plug-in](https://github.com/khalim19/gimp-plugin-export-layers/archive/master.zip) (it should be stable as-is). Once you open the plug-in, check "Show More Settings" at the bottom of the plug-in dialog (not the GIMP window) and then check "Inherit transparency from layer groups".

**Comment by Reptorian1125** [comment]
It is working. Wow, it really does work. I like it. Feel free and respond and then close this as this has been solved.

**Comment by khalim19** [comment]
Great! Closing this issue.
