### ISSUE TITLE
Ignored layers are saved as "Untitled"

### ISSUE THREAD

**Issue by moi90** [khalim19/gimp-plugin-export-layers#43]
I'm using version 2.5.

Under "Advanced Settings" I selected "Ignore" for "[Tagged] layers", but the layers "[bboxes]" and "[contrast]" are exported as "Untitled.png" and "Untitled (1).png".

**Comment by khalim19** [comment]
My intention was to only ignore tags that the plug-in processes ("[background]", "[foreground]"), but it makes sense for any tagged layers to be ignored. My assumption was that the user wanted to treat other tags as parts of the layer name, since they don't do anything. Either way, I made the change.

If one wants to ignore layers with specific tags, I'm going to hopefully make it possible in 3.1 when I plan to add custom operations and filters.

**Comment by khalim19** [comment]
As of version 3.3, the plug-in supports including/excluding layers with arbitrary tags.
