### ISSUE TITLE
Doesn't seem to work in Gimp 2.9

### ISSUE THREAD

**Issue by synk-a-dynka** [khalim19/gimp-plugin-export-layers#45]
Doesn't show up in the menus of 2.9.5 (commit 12ac114).

**Comment by khalim19** [comment]
Since this is another report of the plug-in not working in the development version of GIMP, I took a look at it.

Are you building GIMP yourself or you're using an existing build?

I installed the unofficial build for Windows from [Partha](http://www.partha.com/) and I found out that there are some Python modules missing (that this plug-in is using):
* `logging`
* `importlib`, `unittest` - they are not necessary for running the plug-in itself

To fix this, the easiest way would be to copy the missing modules from the GIMP 2.8 install directory (e.g. `Program Files/GIMP 2/Python/lib` in Windows) to your 2.9.5 install directory (where Python modules are located). In case of the missing `logging` module, copy the `logging` directory.

**Comment by synk-a-dynka** [comment]
I'm using the appimage from Pixl.us: https://discuss.pixls.us/t/community-built-software/2137
As it is a self-contained image there are no lib-folder to copy the modules to.
I'll have to install from source and see if I can get it to work there.

**Comment by khalim19** [comment]
I installed the AppImage on Ubuntu and I got it to work. You need to copy the plug-in to `[home folder]/.config/GIMP-AppImage/plug-ins`.

**Comment by khalim19** [comment]
Since GIMP 2.9 was a development version and 2.10 is officially released, I am closing this issue.
