### ISSUE TITLE
Gimp dir can't be found for installation

### ISSUE THREAD

**Issue by drpeppercan** [khalim19/gimp-plugin-export-layers#63]
#### What went wrong?
I can't install it.
According to the Documentation/Installation info I am to find the GIMP directory here:
"/home/[your username]/.config/GIMP/2.10/plug-ins"
Problem is, there's no such directory according to my Terminal: 
```
/home $ find /home GIMP
find: ‘GIMP’: No such file or directory

```
I also did a seach with the File Browser. I did find the .config dir, but there's no GIMP dir inside.

I don't know if it has anything to do with the fact that I installed Gimp 2.10 with Flatpak:
https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref

#### Configuration

Version of Export Layers: 3.2.1

Version of GIMP: 2.10

Operating system: Linux Mint (Sylvia)

**Comment by khalim19** [comment]
To find out the location of the `plug-ins` folder in your GIMP installation, go to `Edit → Preferences → Folders → Plug-Ins` and use one of the listed folders. You can then specify the path to the `plug-ins` folder for the `-i` option.

Since the flatpak format is now provided on the official GIMP page, I'll update the plug-in installer to detect the GIMP folder automatically when installed by flatpak.

**Comment by khalim19** [comment]
In the end, I decided not to add support for flatpaks for Linux and macOS installers as I removed them starting from version 3.3 [due to their unreliability](https://github.com/khalim19/gimp-plugin-export-layers/issues/65#issuecomment-445491489). Only [installation via ZIP archive](https://khalim19.github.io/gimp-plugin-export-layers/sections/Installation.html#linux) is now provided.
