### ISSUE TITLE
Error: The specified GIMP installation is not supported.

### ISSUE THREAD

**Issue by meredith-wenjunwu** [khalim19/gimp-plugin-export-layers#65]
#### What went wrong?
During installation, there's an error. The error message says "Error: The specified GIMP installation ('/Applications/GIMP.app/Contents/MacOS/GIMP') is not supported. Please install GIMP 2.8 or later or specify custom path to GIMP with the -g option and the plug-in installation path with the -i option."

I tried with -g and -i option. Still the same thing. 

#### If you can, tell us the steps to reproduce the problem.
Not sure how to reproduce since it's an installtion problem

#### Configuration

Version of Export Layers: 3.2.1

Version of GIMP: 2.10.6

Operating system: macOS High Sierra 10.13.4

**Comment by khalim19** [comment]
Try the manual install (the ZIP archive), that should work. Check the [instructions](https://khalim19.github.io/gimp-plugin-export-layers/sections/Installation.html#macos-1) if needed.

For the next version, I'm thinking of removing the installer scripts for Linux and macOS altogether due to how unreliable they are to use (different installation paths, using portable installations, etc.), when it's really about copying a file and a folder.

**Comment by khalim19** [comment]
I decided to remove Linux and macOS installers starting from version 3.3 as previously stated. Installing via the ZIP archive should be simple enough anyway.
